AWSTemplateFormatVersion: '2010-09-09'
Description: Enable AWS Security Hub with CIS AWS Foundations and AWS Foundational Security Best Practices

Resources:
  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties:
      ControlFindingGenerator: SECURITY_CONTROL
      EnableDefaultStandards: true

  CISStandard:
    Type: AWS::SecurityHub::Standard
    DependsOn: SecurityHub
    Properties:
      StandardsArn: !Sub 'arn:aws:securityhub:${AWS::Region}::standards/cis-aws-foundations-benchmark/v/1.4.0'

  AWSFoundationalStandard:
    Type: AWS::SecurityHub::Standard
    DependsOn: SecurityHub
    Properties:
      StandardsArn: !Sub 'arn:aws:securityhub:${AWS::Region}::standards/aws-foundational-security-best-practices/v/1.0.0'

Outputs:
  SecurityHubArn:
    Description: Security Hub ARN
    Value: !Ref SecurityHub
    Export:
      Name: !Sub '${AWS::StackName}-HubArn'
